export const sections = [
  {
    id: "background",
    label: "Your Background",
    icon: "◈",
    questions: [
      {
        id: "role",
        type: "single",
        text: "Which best describes you right now?",
        options: [
          "I have an idea I haven't acted on yet",
          "I'm actively building something",
          "I've launched something before",
          "I invest in or advise early-stage ventures",
          "I work in a community or development organisation",
        ],
      },
      {
        id: "domain",
        type: "multi",
        text: "What areas do your ideas or work touch? (Select all that apply)",
        options: [
          "Technology & Software",
          "Agriculture & Food Systems",
          "Climate & Environment",
          "Community & Social Impact",
          "Finance & Fintech",
          "Health & Wellbeing",
          "Education",
          "Other",
        ],
      },
      {
        id: "geography",
        type: "single",
        text: "Where are you primarily based?",
        options: [
          "Sub-Saharan Africa",
          "North Africa / Middle East",
          "South / Southeast Asia",
          "Europe",
          "North America",
          "Latin America",
          "Other",
        ],
      },
    ],
  },
  {
    id: "idea_pain",
    label: "Ideas & Validation",
    icon: "◉",
    questions: [
      {
        id: "idea_confidence",
        type: "scale",
        text: "When you have an idea, how confident are you that it solves a real problem people will pay for?",
        labels: ["Not at all confident", "Very confident"],
      },
      {
        id: "idea_blockers",
        type: "multi",
        text: "What has stopped you from moving forward with an idea? (Select all that apply)",
        options: [
          "Not sure if people actually want it",
          "Don't know where to start strategically",
          "Hard to find the right team or collaborators",
          "No structured way to test it quickly",
          "Difficult to explain it to potential partners or funders",
          "Overwhelmed by how many tools and steps are involved",
          "Nothing — I move quickly once I have an idea",
        ],
      },
      {
        id: "validation_method",
        type: "single",
        text: "How do you currently figure out if an idea has legs?",
        options: [
          "I ask friends and family",
          "I research online manually",
          "I post in communities and see the reaction",
          "I build a quick prototype and test it",
          "I don't — I just start building",
          "I don't have a consistent method",
        ],
      },
    ],
  },
  {
    id: "execution_pain",
    label: "Strategy & Execution",
    icon: "◎",
    questions: [
      {
        id: "strategy_gap",
        type: "scale",
        text: "How difficult do you find it to turn an idea into a clear, structured plan others can follow?",
        labels: ["Very easy", "Extremely difficult"],
      },
      {
        id: "execution_struggles",
        type: "multi",
        text: "Which execution challenges have you personally experienced? (Select all that apply)",
        options: [
          "Unclear milestones — didn't know what to do next",
          "No way to measure if we were making real progress",
          "Team wasn't aligned on priorities",
          "Spent time on the wrong things",
          "Couldn't communicate progress to stakeholders",
          "Lost momentum after early excitement faded",
        ],
      },
      {
        id: "tools_fragmented",
        type: "single",
        text: "How many different tools or platforms do you currently use to manage an idea from concept to launch?",
        options: [
          "1–2 (pretty simple)",
          "3–5 (manageable)",
          "6–10 (it's a lot)",
          "More than 10 (chaotic)",
          "I don't use any structured tools",
        ],
      },
    ],
  },
  {
    id: "community_ideas",
    label: "Community & Impact Ideas",
    icon: "⬡",
    questions: [
      {
        id: "impact_idea_type",
        type: "multi",
        text: "Have you ever had an idea to address any of the following? (Select all that apply)",
        options: [
          "A farming or food access problem in your community",
          "A climate or environmental challenge",
          "A public health or sanitation issue",
          "An infrastructure problem (roads, energy, water)",
          "Economic inclusion or poverty reduction",
          "Youth development or education access",
          "I haven't had ideas in these areas",
        ],
      },
      {
        id: "impact_barrier",
        type: "single",
        text: "What is the biggest barrier when you have an idea meant to help a community or address a global challenge?",
        options: [
          "I don't know how to turn it into a real project",
          "No platform to share it where it can get traction",
          "Hard to find people or organisations willing to fund or support it",
          "The idea feels too big to tackle alone",
          "I'm not sure who the right stakeholders are",
          "I've never had such an idea",
        ],
      },
      {
        id: "community_collab",
        type: "scale",
        text: "How valuable would it be to have a dedicated space where community and global-impact ideas are surfaced, refined collaboratively, and converted into structured projects?",
        labels: ["Not valuable", "Extremely valuable"],
      },
    ],
  },
  {
    id: "platform_fit",
    label: "Platform Fit",
    icon: "◇",
    questions: [
      {
        id: "unified_platform",
        type: "scale",
        text: "How appealing is the idea of a single platform that takes you from raw idea → validated concept → structured execution → investor-ready?",
        labels: ["Not appealing", "Extremely appealing"],
      },
      {
        id: "credibility_score",
        type: "single",
        text: "If your startup or project had a publicly visible credibility score based on real execution data, how would that affect you?",
        options: [
          "It would strongly motivate me to move faster",
          "It would help me attract partners and funders more easily",
          "It would create unnecessary pressure",
          "I wouldn't care either way",
          "I'd want more control over what's visible",
        ],
      },
      {
        id: "must_have",
        type: "single",
        text: "Imagine you had access to this kind of platform today. How would you feel if it disappeared tomorrow?",
        options: [
          "Very disappointed — I'd have no good alternative",
          "Somewhat disappointed — but I'd find workarounds",
          "Not disappointed — I can manage without it",
          "I'm not sure yet",
        ],
      },
    ],
  },
  {
    id: "closing",
    label: "Final Thoughts",
    icon: "◆",
    questions: [
      {
        id: "recommend",
        type: "scale",
        text: "How likely are you to recommend a platform like this to someone building something?",
        labels: ["Would not recommend", "Would strongly recommend"],
      },
      {
        id: "open_feedback",
        type: "textarea",
        text: "What's one thing a platform like this absolutely must get right to be useful to you?",
        placeholder: "Share your honest thought here…",
      },
      {
        id: "early_access",
        type: "single",
        text: "Would you be interested in early access when this platform is ready?",
        options: [
          "Yes — sign me up",
          "Yes — but only if it fits my use case",
          "Maybe, I'd like to learn more first",
          "Not at this time",
        ],
      },
    ],
  },
]
